###

POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "Maria",
   "email": "maria@teste.com" ,
   "password": "123456",
   "role": "ADMIN"
}


### 
POST http://localhost:3003/user/login
Content-Type: application/json

{
   "email": "janana@teste.com" ,
   "password": "123456"
}


###
GET http://localhost:3003/user/profile

###
POST http://localhost:3003/recipe
Content-Type: application/json

{
   "name": "pastel de ar" ,
   "description": "muita massa"
}